### PR TITLE
upgrade Python version to 3.5.2

### PR DESCRIPTION
**Pull request by IshmeetKaur**
Upgrading Python Version to 3.5.2

### CODE REVIEW

**Review by FRosner — CHANGES_REQUESTED** [review]
Can we upgrade Anaconda to the latest version as well? I think it is 4.4.0 or something.

**Review by FRosner — APPROVED** [review]
Nevermind, we need to have Python 3.5 so this is the right Anaconda version. Spark doesn't work with 3.6, yet.

**Comment by FRosner** [comment]
@IshmeetKaur can we look at it together to see that everything still works as expected?

**Comment by IshmeetKaur** [comment]
@FRosner  yes.. Let me know whenever you are free :)

**Pull request merged**
